language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm test
  - npm run cover

notifications:
  email:
    on_success: never
    on_failure: always

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"